### ISSUE TITLE
write to packages.cson upon package install/uninstall

### ISSUE THREAD

**Issue by travi** [jamescmartinez/parcel#5]
I use my dotfiles across multiple architectures (OSX, Linux, and Windows in GitBash). I version `packages.cson` there to keep my settings in sync wherever I use atom. There are some packages that simply do not work on all architectures, `auto-update-packages` and `svg-preview` to name a few.

It seems that `parcel` writes the current state of installed plugins to `packages.cson` rather than updating upon installation and uninstallation. The problem with this is that it does not handle installation failures as I would expect. I can understand some packages not working everywhere, but I still want `parcel` to install them when possible. 

Instead, an installation failure results in that package being removed from `packages.cson` and I end up having to take extra steps to ensure that I don't commit that change and push it to other machines. It has also resulted in merge conflicts on multiple occasions.

Instead of tracking current state, could writes be triggered based on installation and uninstallation in order to handle architecture differences?

**Comment by jgillich** [comment]
+1, I've also had it remove packages for no apparent reason.

**Comment by jamescmartinez** [comment]
Hi @travi @jgillich,

I haven't been using/working on this package lately. Though I may pick it up again soon, I'd welcome any pull requests that fix this issue.

**Comment by travi** [comment]
i've moved to [package-sync](https://atom.io/packages/package-sync), which seems to cover this need.
