### ISSUE TITLE
parcel breaks symlinked packages.cson

### ISSUE THREAD

**Issue by yourpalal** [jamescmartinez/parcel#6]
I set up a symlink for my packages.cson so that it could be managed with [gnu stow](https://www.gnu.org/software/stow/). Unfortunately, parcel deletes the current packages.cson before writing to it @ [lib/package-list.coffee:25](https://github.com/jamescmartinez/parcel/blob/master/lib/package-list.coffee#L25).

The unlinking code was introduced in 61839a3cfab07331640961f6f31df7ddf5f9d81d. I have tried deleting this code and everything seems to work fine on my machine, but it's not obvious to me why the unlinking was introduced in the first place. I can make a pull request with this change if you'd like.

**Comment by jamescmartinez** [comment]
This package is no longer maintained. Sorry!
